pipeline {
    agent any
    tools {
        maven 'Maven 3.8.4'
        jdk 'openjdk'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH_SH = ${PATH}"
                    echo "M2_HOME_SH = ${M2_HOME}"
                '''
                echo "PATH = ${PATH}"
                echo "M2_HOME = ${M2_HOME}"
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}